# Generated by Django 6.0.6 on 2026-06-17 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0001_initial'),
        ('recyclebin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclebin',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filesystem.directory'),
        ),
        migrations.AddField(
            model_name='recyclebin',
            name='permission',
            field=models.CharField(default='WRITE', max_length=20),
        ),
    ]
